//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductEvalation.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedBack_FeedBackDetail
    {
        public Nullable<int> FeedBack_ID { get; set; }
        public Nullable<int> FeedBakcDetailID { get; set; }
        public int FFID { get; set; }
    
        public virtual FeedBack FeedBack { get; set; }
        public virtual FeedBackDetail FeedBackDetail { get; set; }
    }
}
