//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductEvalation.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedBack
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FeedBack()
        {
            this.FeedBack_FeedBackDetail = new HashSet<FeedBack_FeedBackDetail>();
        }
    
        public int ReturnID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ProductID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeedBack_FeedBackDetail> FeedBack_FeedBackDetail { get; set; }
        public virtual Products Products { get; set; }
        public virtual Users Users { get; set; }
    }
}
