//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductEvalation.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProductEva_Entities1 : DbContext
    {
        public ProductEva_Entities1()
            : base("name=ProductEva_Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<FeedBack> FeedBack { get; set; }
        public virtual DbSet<FeedBack_FeedBackDetail> FeedBack_FeedBackDetail { get; set; }
        public virtual DbSet<ProductCategory> ProductCategory { get; set; }
        public virtual DbSet<Sells> Sells { get; set; }
        public virtual DbSet<V_Categories> V_Categories { get; set; }
        public virtual DbSet<V_FeedBakDetail> V_FeedBakDetail { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<V_Product_V> V_Product_V { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<FeedBackDetail> FeedBackDetail { get; set; }
    }
}
