//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductEvalation.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_FeedBakDetail
    {
        public long RowId { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> UserID { get; set; }
        public int FeedBackDetail_ID { get; set; }
        public Nullable<int> Dayanıklılık { get; set; }
        public Nullable<int> DısGörünüs { get; set; }
        public Nullable<int> FiyatPerf { get; set; }
        public Nullable<int> Kalite { get; set; }
        public Nullable<int> KullanımKolaylıgı { get; set; }
        public string UserReview { get; set; }
        public string CompanyReview { get; set; }
    }
}
