//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductEvalation.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Product_V
    {
        public long RowId { get; set; }
        public int ProductID { get; set; }
        public string PName { get; set; }
        public string CategoryName { get; set; }
        public string ProductCategoryName { get; set; }
        public string Color { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string CompanyName { get; set; }
        public string IMG { get; set; }
    }
}
